import Head from 'next/head';
import HeroSection from '@/components/sections/HeroSection';
import EducationSection from '@/components/sections/EducationSection';
import ContentSection from '@/components/sections/ContentSection';
import NewsSection from '@/components/sections/NewsSection';
import ImpactSection from '@/components/sections/ImpactSection';
import LookSection from '@/components/sections/LookSection';
import AmsterdamSection from '@/components/sections/AmsterdamSection';
import CalendarSection from '@/components/sections/CalendarSection';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
      <HeroSection />
      <EducationSection/>
      <ImpactSection/>
      <NewsSection/>
      <CalendarSection/>
      <AmsterdamSection/>
      <LookSection/>
      <ContentSection/>
      </main>
    </>
  )
}
